name: Wechat_sign_in_SCU
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        - run: chrome --version
          with:
          chrome-version: latest
          - name: Set up Python 3.9
            uses: actions/setup-python@v2
            with:
                python-version: '3.6'
                architecture: 'x64'
          - run: python my_script.py
          - uses: actions/checkout@v2



