name: Wechat_sign_in_SCU
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 21 * * *'

jobs:
  start:
      runs-on: windows-latest
      steps:
        #安装chrome
        - name: Install Chrome
          uses: browser-actions/setup-chrome@latest
        - run: chrome --version
          with:
          chrome-version: latest
        #安装Python环境
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: '3.6'
            architecture: 'x64'
        - run: python my_script.py
        #checkout 自己的代码
        - uses: actions/checkout@v2
        #安装配置文件
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        #开始运行自己的代码
        run: |
          cd SCU_Wechat_Sign_in
          python post.py

