# This is a basic workflow to help you get started with Actions

name: wechatlogin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 安装chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      #安装Chromedriver
      - uses: nanasess/setup-chromedriver@v1
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '97.0.4692.71'
      - run: chromedriver --url-base=/wd/hub &
      # Runs a set of commands using the runners shell
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: run_my_program
        env:
          PASSWD: ${{ secrets.WECHAT_PASSWD }}
          USR_NAME: ${{ secrets.WECHAT_USR_NAME }}
        run: python post.py
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: mtp.163.com
      # Optional port (defaults to 465)
          port: 465
          account: ${{ secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: Guchenyu
          from: GitHub Actions
          to: 1549159420@qq.com
          subject: Daka result
          body: file://result.txt
      # Optional content type (defaults to text/plain)
          contentType: text/plain
      # Optional attachment files (JSON type. require property 'path')
          attachments: ''
